name: Backend CI

on:
  push:
    paths:
      - 's1213_spring_home_final/SSAFYHOME/**'
    branches:
      - main
  pull_request:
    paths:
      - 's1213_spring_home_final/SSAFYHOME/**'
    branches:
      - main

jobs:
  pr-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x s1213_spring_home_final/SSAFYHOME/gradlew

      - name: Build and Test
        run: |
          cd s1213_spring_home_final/SSAFYHOME/backend
          ./gradlew build

  push-deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x s1213_spring_home_final/SSAFYHOME/gradlew

      - name: Build without Test
        run: |
          cd s1213_spring_home_final/SSAFYHOME/backend
          ./gradlew build -x test

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          cd s1213_spring_home_final/SSAFYHOME/
          docker build -t myapp-backend:latest .

      - name: Push Docker Image
        run: |
          docker tag myapp-backend user/myapp-backend:latest
          docker push user/myapp-backend:latest
